[project]
name = "image-classificaiton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.25.0",
    "opencv-python>=4.8.0",
    "pillow>=10.0.0",
    "streamlit>=1.26.0",
    "tensorflow>=2.13.0",
]
